library(tidyverse)
test <- as.tbl(read.csv("Data/poker-hand-testing.data", header = FALSE))
colnames(test) <- c("suit1","rank1","suit2","rank2","suit3","rank3","suit4","rank4","suit5","rank5","class")
train <- as.tbl(read.csv("Data/poker-hand-training-true.data", header = FALSE))
colnames(train) <- c("suit1","rank1","suit2","rank2","suit3","rank3","suit4","rank4","suit5","rank5","class")
classdf <- tibble(0:9,c("nothing in hand", "one pair", "two pair","three of a kind", "straight", "flush", "full house", "four of a kind", "straight flush", "royal flush"))
colnames(classdf) <- c("class", "hand")
suit <- tibble(1:4, c("hearts", "spades", "diamonds", "clubs"))
colnames(suit) <- c("code", "suit")
data <- rbind(train, test)
datachar <- data %>% mutate(suit1 = suit$suit[data$suit1])
datachar <- datachar %>% mutate(suit2 = suit$suit[data$suit2])
datachar <- datachar %>% mutate(suit3 = suit$suit[data$suit3])
datachar <- datachar %>% mutate(suit4 = suit$suit[data$suit4])
datachar <- datachar %>% mutate(suit5 = suit$suit[data$suit5])
datachar <- datachar %>% mutate(class = classdf$hand[data$class+1])

data %>% group_by(class) %>% summarise(mean(rank5))

